### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [fringsoo/pragmatics_game#1]
Hi, amazing paper :) And thank-you very much for providing code :) Don't suppose... could it be possible to add a license to this code? E.g. MIT is quite nice https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt

**Comment by fringsoo** [comment]
Hi, Hugh. Thanks for your interest in our project and the reminder about the license! I have committed a new version with a license.

**Comment by hughperkins** [comment]
Awesome! Thank you :)
